import type { Metadata } from 'next'
import { Merriweather, Open_Sans } from 'next/font/google'

const merriweather = Merriweather({
  variable: '--font-heading',
  subsets: ['latin'],
})

const openSans = Open_Sans({
  variable: '--font-body',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${merriweather.variable} ${openSans.variable}`}>
      <body>{children}</body>
    </html>
  )
}
